### ISSUE TITLE
The example/debug.py problem.

### ISSUE THREAD

**Issue by wcc526** [selectel/pyte#46]
When I run the example/debug.py,I got this traceback.

Traceback (most recent call last):
  File "debug.py", line 27, in <module>
    stream.feed(blob)
  File "/Users/wcc526/.virtualenvs/fortress/lib/python2.7/site-packages/pyte/streams.py", line 378, in feed
    return super(ByteStream, self).feed(chars)
  File "/Users/wcc526/.virtualenvs/fortress/lib/python2.7/site-packages/pyte/streams.py", line 166, in feed
    send(char)
  File "/Users/wcc526/.virtualenvs/fortress/lib/python2.7/site-packages/pyte/streams.py", line 313, in _parser_fsm
    dispatch(csi[char], *params, private=True)
  File "/Users/wcc526/.virtualenvs/fortress/lib/python2.7/site-packages/pyte/streams.py", line 215, in dispatch
    handler(*args, **kwargs)
TypeError: report_device_attributes() takes exactly 1 argument (3 given)

**Comment by superbobry** [comment]
Thanks, as they say, "if it's untested, it's broken" :)
